### ISSUE TITLE
Question: Is an API to this project considered for the future?

### ISSUE THREAD

**Issue by Suppenterrine** [Jason-xy/CyberReader#7]
Hello, I read the project summary and I like the use case.
I didn't try it yet. But I got the idea or thought that it would be practical to offer something API like. 
So that other apps or services could quickly hook in on this specific use case and retrieve the results.

This is just quick thought / idea and I'm curios.
Looking forward to a short answer.

Have a really nice day! 👋

**Comment by Jason-xy** [comment]
👋Thank you for your interest in this project! This project was designed from the start to be a ready-to-use local application. You only need to install the dependencies with conda to launch the GUI. Currently there is no plan to make it a service API, because the program involves model inference during runtime, which requires substantial computing resources. We do not have enough spare resources to support such a service yet. Of course, you are also welcome to build upon this project to enable server-side deployment.

**Comment by Suppenterrine** [comment]
Thank you for the detailed answer!
